### ISSUE TITLE
Feature Request: Improve PROTECT error reporting.

### ISSUE THREAD

**Issue by StanHash** [FireEmblemUniverse/ColorzCore#1]
```
PROTECT 0xC00000 0x1000000
ORG 0xC00000
WORD 0xDEADBEEF
```

Doesn't yield any errors.

From a quick look through `Parser/EAParser.cs`: [`IsProtected`](https://github.com/FireEmblemUniverse/ColorzCore/blob/master/ColorzCore/Parser/EAParser.cs#L799) seems to not be referenced anywhere, and [`protectedRegions`](https://github.com/FireEmblemUniverse/ColorzCore/blob/master/ColorzCore/Parser/EAParser.cs#L49) is only ever written to outside of it. Both members are private so it's safe to assume they aren't referenced outside of this file either.

pls fix kthx

**Comment by Crazycolorz5** [comment]
That's.... quite interesting, because it has worked previously. I'll look into it.

**Comment by Crazycolorz5** [comment]
I'd like to report what memory location (i.e. which protected region) is being violated when this errors.
