### ISSUE TITLE
Bugfig: Error in lexing

### ISSUE THREAD

**Issue by Crazycolorz5** [FireEmblemUniverse/ColorzCore#10]
// simple ignores the rest of the lane so the following code which should be valid isn't:

/*
// */

**Comment by StanHash** [comment]
Can't reproduce? The code you gave seems already valid?
Am I missing something?

---

```c
/*
MESSAGE inside
// */ MESSAGE outside
MESSAGE after
```
```
In File Main.event, Line 3, Column 7: outside 
In File Main.event, Line 4, Column 1: after 
```

---

```c
//*
MESSAGE inside
// */ MESSAGE outside
MESSAGE after
```
```
In File Main.event, Line 2, Column 1: inside 
In File Main.event, Line 4, Column 1: after 
```

**Comment by Crazycolorz5** [comment]
Sorry, I think it'd be
```
// /* comment
*/
```
that should error

**Comment by StanHash** [comment]
// /* comment
    */

in NL!Core:

    1 errors encountered:
    File: Main.event, Line: 2: Error removing comments

It breaks.

(and yes this is also invalid in C (see this [ISO C99 standard pdf (6.4.9)](http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf) which implies that comment delimiters are only to be considered as such when they aren't already within a comment (and other stuff))).
