### ISSUE TITLE
Feature: Add warning when writing before first ORG

### ISSUE THREAD

**Issue by StanHash** [FireEmblemUniverse/ColorzCore#15]
As requested, this is the feature request issue corresponding to #13 . The feature is already implemented; It's just a matter of getting everyone's approval.

The idea behind all of this is just to help prevent users from making dumb mistakes.

**Comment by StanHash** [comment]
I'll address @Crazycolorz5's https://github.com/FireEmblemUniverse/ColorzCore/pull/13#issuecomment-429703357 here.

---

>Interesting design proposal. Mind writing it up as a feature proposal in Issues so I can direct FEU discussion to it?

Here it is.

>I think the idea has merit but I am a bit concerned about potential cases as this would make valid programs a strict subset of before.

I don't want to break any compatibily either; If that's what you're saying. This is why I'm proposing this to just emit a warning. In general I'd say that adding warnings where we can to help the user find unwanted behavior

In general I think there is gain to add more warnings when we can detect slight issues. (For example, I'm considering proposing a warning when including files whose name don't match the case given in the include expression (ex: `#include "eastdlib.event"` vs `#include "EAstdlib.event"`) as it only works on some platforms (Windows)).

>That said, I don't think any genuine EA script before legitimately wanted to write to 0.
>
>But if someone was using it for binary file manipulation (which I can see as possible), then it might break those....
>
>But there are probably very few cases of those and such people shouldn't have issue writing an ORG 0.

This is also why I suggested adding this as an option.

In addition to this, if we ever get to the point where we want to output some kind of relocatable instead of writing to a straight binary; not having an `ORG` may actually be *preferred*; as it's absence would maybe denote that the data written is of the relocatable kind. So if we go down that route we *will* want this to be toggle-able (at least internally).

>(Nevertheless, would like to hear more opinions).

Yes!

**Comment by Crazycolorz5** [comment]
Seeing as this is just a warning, I'm letting this go through. I've merged the proposed PR (#13).
