### ISSUE TITLE
Bug?: Can't create a new output file (only edit existing binaries)

### ISSUE THREAD

**Issue by StanHash** [FireEmblemUniverse/ColorzCore#30]
This isn't a big deal for the main purpose this tool historically had (which is: modifying existing binaries); but it may be worth looking at making this possible, if only to make it seem more plausible that snek was made using this and not NL!EA \:p

**Comment by Crazycolorz5** [comment]
Huh, I was actually under the impression Leo did use this. Should be a pretty easy change to snipe.
