### ISSUE TITLE
Suggestion: unary not operator

### ISSUE THREAD

**Issue by StanHash** [FireEmblemUniverse/ColorzCore#42]
Would flip bits

Hypothetical usage example:

    scIgnoreAllKeysButA:
        IGNORE_KEYS (KeyAll & (~KeyButtonA))
        ENDA

**Comment by Crazycolorz5** [comment]
Unary operator is kinda gross parsing wise but I guess it makes sense to have? 

Workaround:
`#define Not(x) "(x^0xFFFFFFFF)" `
(I think we have xor? If not it IS buildable from and and or...)
