### ISSUE TITLE
Inline braces don't work

### ISSUE THREAD

**Issue by sme23** [FireEmblemUniverse/ColorzCore#60]
When putting curly braces inline like `{ #include "file" }` the closing brace isn't parsed.

**Comment by Crazycolorz5** [comment]
`#command` is supposed to be on its own line, in part due to the rest of the parameters being passed raw to the command (to allow for things such as strings being passed to `incext`.

Does this work if you do
```
{
#include "file"
}
```
Or is it still nonfunctioning in that case?

**Comment by sme23** [comment]
Yeah it works on separate lines, probably just me misunderstanding how this is supposed to work, sorry
